name: Manual workflow

on:
  push:
  workflow_dispatch:
  
jobs:
  run_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v1
    
    - run: ls ${{ github.workspace }}
    - name: Install dependencies
      run: npm install
    - name: Run test
      run: npm run wdio
