name: Manual workflow

on:
  push:
  workflow_dispatch:
  
jobs:
  run_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: ./

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - run: ls ${{github.workspace}}
    - name: Install dependencies
      working-directory: ${{ github.workspace }}/${{ env.PROJECT_PATH }}
      run: npm install
    - name: Run test
      run: npm run wdio
